// 12 Blog articles with header images, categories and full content
export const BLOG_POSTS = [
  {
    slug: 'ai-transforming-indian-smbs-2026',
    title: 'How AI Is Quietly Transforming Indian SMBs in 2026',
    excerpt: 'The AI revolution isn’t happening at Google or OpenAI — it’s happening at a saree shop in Surat, a hospital in Coimbatore, and a broker in Ahmedabad. Here’s how.',
    image: 'https://images.unsplash.com/photo-1652156752342-c786f1e1d1ce',
    category: 'AI & Automation',
    tags: ['AI', 'SMB', 'Automation'],
    author: 'Aarav Mehta',
    role: 'Founder & CEO',
    date: '2026-06-14',
    readMin: 7,
    content: [
      'For a decade, Indian small businesses have watched the AI hype cycle from the sidelines. “ChatGPT is for the Bay Area,” they’d say. “We still can’t get GST reconciliation right.” In 2026, that changed.',
      'This year, we deployed AI systems for 87 Indian SMBs — a saree wholesaler that now uses an AI agent to answer WhatsApp queries in Gujarati; a diagnostic lab that reads handwritten prescriptions via OCR; a real-estate broker whose AI dials 400 leads a day. None of them have a data science team.',
      'The unlock is not a smarter model — it’s cheaper models, better integration and Indian-language support. Gemini Flash costs less than a WhatsApp message. Multilingual understanding is now table-stakes.',
      'If you’re a business owner reading this, the single biggest ROI you can unlock in the next 90 days is a WhatsApp AI agent. Every lead answered instantly. No missed calls. No follow-ups slipping. That is a 20–35% revenue bump for most SMBs — for less than the cost of one part-time salesperson.',
      'The businesses that adopt AI in 2026 will not be the ones with the biggest budgets. They’ll be the ones with the courage to try one small experiment this month.',
    ],
    key: 'ai_transformation',
  },
  {
    slug: 'crm-vs-excel-real-cost',
    title: 'CRM vs Excel: The Hidden Cost of “We’re Fine With Sheets”',
    excerpt: 'Most sales teams think they’re saving money with spreadsheets. We calculated the true cost across 40 businesses — the answer will shock you.',
    image: 'https://images.unsplash.com/photo-1649767428212-7590dbf20116',
    category: 'CRM & Sales',
    tags: ['CRM', 'Sales', 'Productivity'],
    author: 'Priya Nair',
    role: 'Chief Product Officer',
    date: '2026-06-08',
    readMin: 6,
    content: [
      'Sales leaders love Excel. It’s free, it’s familiar and everyone knows how to use it. But we recently audited 40 mid-sized businesses that ran their sales on spreadsheets — and the results were sobering.',
      'On average, a 6-person sales team spent 22 hours per week updating sheets, chasing lead status, reconciling versions and building pivot reports for the boss. That’s more than half a full-time employee’s output — gone to administrative work.',
      'Worse, 18–24% of leads were slipping through the cracks. Follow-ups missed because someone forgot to check the sheet. Deals lost because the wrong version was shared with the customer. It adds up to a real, measurable revenue leak.',
      'A modern CRM — like Oli CRM — fixes this in under 30 days. AI reminders push follow-ups. WhatsApp integration captures leads automatically. Pipeline visibility is real-time. Reports are one click.',
      'The math is straightforward: at ₹15,000 per year for the whole team, most businesses see 10× ROI in the first quarter. Sometimes “free” is the most expensive thing you own.',
    ],
    key: 'crm_excel',
  },
  {
    slug: 'whatsapp-automation-lead-generation',
    title: 'WhatsApp Automation: The Playbook Every Indian Business Should Steal',
    excerpt: '90% of Indian customers prefer WhatsApp. But most businesses use it manually. Here’s the automation playbook that 3×’d our clients’ conversions.',
    image: 'https://images.pexels.com/photos/6913311/pexels-photo-6913311.jpeg',
    category: 'AI & Automation',
    tags: ['WhatsApp', 'Automation', 'Lead Gen'],
    author: 'Rohan Shah',
    role: 'VP Engineering',
    date: '2026-06-01',
    readMin: 5,
    content: [
      'India runs on WhatsApp. 550 million users. 90% preferring WhatsApp over phone or email. And yet most businesses still copy-paste responses manually.',
      'The WhatsApp Business API changed everything two years ago. You can now broadcast, auto-reply, tag, segment and route conversations — all from one dashboard. Combined with an AI agent, WhatsApp becomes your 24×7 lead generation engine.',
      'The playbook we deploy for clients is simple: (1) capture WhatsApp opt-ins on your website; (2) send a welcome message with your best offer; (3) auto-qualify leads via AI in Hindi/Gujarati/English; (4) route hot leads to human sales; (5) drip nurture cold leads for 30 days.',
      'Results across 60+ deployments: 3.2× more qualified conversations, 40% lower CAC and 2.1× conversion rates. Total setup: 4 weeks. Ongoing cost: less than a junior employee’s salary.',
      'If you’re still replying to WhatsApp manually in 2026, you’re leaving money on the table. Every hour.',
    ],
    key: 'whatsapp_automation',
  },
  {
    slug: 'erp-implementation-manufacturing-guide',
    title: 'The Honest ERP Implementation Guide for Indian Manufacturers',
    excerpt: 'Most ERP projects fail. Not because of software. Because of process. Here’s a battle-tested playbook we’ve used at 40+ Indian factories.',
    image: 'https://images.pexels.com/photos/7653568/pexels-photo-7653568.jpeg',
    category: 'ERP & Operations',
    tags: ['ERP', 'Manufacturing', 'Digital Transformation'],
    author: 'Vikram Rao',
    role: 'AI Lead',
    date: '2026-05-25',
    readMin: 9,
    content: [
      'Every manufacturing CEO we meet has an ERP horror story. Either they spent ₹1 crore on SAP and use 10% of it. Or they bought a cheap tool and abandoned it in year 2. There’s a better way.',
      'The reason ERP projects fail is not technology. It’s process discipline. Most factories try to digitize their existing chaos — and end up with digital chaos.',
      'Our playbook has 5 phases: (1) Process mapping (2 weeks): document what actually happens vs what should happen. (2) Master data cleanup (3 weeks): SKUs, BOMs, vendors, customers — clean it before you migrate. (3) Modular rollout (3 months): start with 1 module, prove ROI, expand. (4) User adoption (ongoing): daily standups, incentives, no going back to Excel. (5) Continuous improvement (quarterly reviews).',
      'The single biggest predictor of ERP success is not the software chosen — it’s whether the owner personally logs in every day for the first 90 days. If leadership is not on the system, no one will be.',
      'Follow this playbook and your ERP will pay for itself in year 1. Ignore it and you’ll join the 70% of factories with expensive software collecting dust.',
    ],
    key: 'erp_guide',
  },
  {
    slug: 'digital-transformation-hospitals',
    title: 'Digital Transformation in Healthcare: 5 Wins in 90 Days',
    excerpt: 'Hospitals don’t need a 3-year digital roadmap. They need 5 quick wins. Here’s exactly what to do in your first 90 days.',
    image: 'https://images.unsplash.com/photo-1472289065668-ce650ac443d2',
    category: 'Healthcare',
    tags: ['Healthcare', 'Digital Transformation', 'Hospital ERP'],
    author: 'Sneha Patel',
    role: 'Head of Design',
    date: '2026-05-18',
    readMin: 6,
    content: [
      'Hospital digital transformation projects fail because they aim too big. “Replace all our systems in 18 months” is a recipe for disaster. Aim for 5 quick wins in 90 days instead.',
      'Win 1 — Online appointments (Week 1–2): a simple booking widget on your website cuts OPD wait times by 40% and marketing spend by 25%.',
      'Win 2 — Digital prescriptions (Week 3–4): doctors write once, patient gets PDF on WhatsApp, pharmacy reads QR code. Zero paper.',
      'Win 3 — Inventory alerts for pharmacy (Week 5–6): auto-reorder points prevent stock-outs and expiry losses. Both are silent profit killers.',
      'Win 4 — Insurance TPA automation (Week 7–8): standardized claim submissions cut rejection rates from 25% to 5%.',
      'Win 5 — Patient satisfaction app (Week 9–12): 3-question NPS after every visit. You’ll learn more in 30 days than in 3 years of feedback forms.',
      'By Week 12, you’ll have measurable improvements in every department — and buy-in from staff to tackle bigger transformations next.',
    ],
    key: 'hospital_transformation',
  },
  {
    slug: 'real-estate-crm-doubled-bookings',
    title: 'The Real Estate CRM That Doubled a Builder’s Bookings in 6 Months',
    excerpt: 'A candid case study from Verma Realty — how a Real Estate CRM took their site-visit-to-booking ratio from 8% to 17%.',
    image: 'https://images.pexels.com/photos/12902992/pexels-photo-12902992.jpeg',
    category: 'Real Estate',
    tags: ['Real Estate', 'CRM', 'Case Study'],
    author: 'Ananya Iyer',
    role: 'Customer Success Head',
    date: '2026-05-10',
    readMin: 5,
    content: [
      'When Verma Realty came to us, their situation was familiar: 400 leads a month across 3 projects, WhatsApp chaos, brokers on WhatsApp groups, and a founder personally calling every lead.',
      'Six months later, their site-visit-to-booking ratio had doubled from 8% to 17%. Nothing changed about their pricing, their brokers or their product. What changed was the CRM.',
      'The three things we did differently: (1) auto-capture leads from 99acres, Facebook, Google Ads and website into one pipeline; (2) WhatsApp broadcast + drip campaigns for cold leads over 30 days; (3) EMI tracker that reduced payment delays by 60%.',
      'The lesson is not that CRMs are magical. It’s that a builder losing 92% of their leads has more upside from a CRM than from more advertising. Fix the leak before opening the tap.',
      'Verma Realty is now expanding to 4 new projects on the same CRM — without adding sales staff.',
    ],
    key: 'real_estate_case',
  },
  {
    slug: 'restaurant-pos-trends-2026',
    title: 'Restaurant POS Trends 2026: What Every Owner Needs to Know',
    excerpt: 'From aggregator sync to captain apps to ONDC integration — 5 restaurant POS trends we’re seeing across 200+ deployments.',
    image: 'https://images.pexels.com/photos/13219418/pexels-photo-13219418.jpeg',
    category: 'Retail & F&B',
    tags: ['Restaurant', 'POS', 'Trends'],
    author: 'Aarav Mehta',
    role: 'Founder & CEO',
    date: '2026-05-04',
    readMin: 6,
    content: [
      'Restaurant tech is moving faster than any industry we serve. Here are the 5 trends we’re seeing across 200+ deployments in 2026.',
      'Trend 1: The captain app is the new POS. Waiters take orders on their phones, KOTs print automatically, and customers get bills faster. Table turnovers up 15–20%.',
      'Trend 2: Aggregator reconciliation is now table-stakes. Zomato and Swiggy skim off ₹8–12 lakh a year on reconciliation errors. A modern POS catches every missed payout.',
      'Trend 3: ONDC integration is the wild card. Early adopters are seeing 10–20% incremental orders with 3–5% lower commissions than aggregators.',
      'Trend 4: Recipe-linked inventory is quietly transforming margins. Every dish sold auto-deducts ingredients. Wastage detected in real time. Margins up 3–5%.',
      'Trend 5: WhatsApp loyalty is replacing SMS coupons. 60% higher open rates and 3× redemption. This is the single biggest marketing lever we see.',
      'If your POS can’t do all 5 of these in 2026, you’re running yesterday’s restaurant on yesterday’s system.',
    ],
    key: 'restaurant_trends',
  },
  {
    slug: 'retail-inventory-mistakes',
    title: '7 Retail Inventory Mistakes Silently Killing Your Margins',
    excerpt: 'Every retail owner obsesses about revenue. Almost none obsess about inventory. Here are 7 mistakes we see — and how to fix them.',
    image: 'https://images.unsplash.com/photo-1573867607590-361ea324975e',
    category: 'Retail & F&B',
    tags: ['Retail', 'Inventory', 'Margins'],
    author: 'Priya Nair',
    role: 'Chief Product Officer',
    date: '2026-04-28',
    readMin: 7,
    content: [
      'Retail is a game of inches. A 2% inventory improvement can double your net margin. And yet, retailers make the same 7 mistakes over and over.',
      'Mistake 1: No stock accuracy discipline. If your system says 12 pieces but the shelf has 8, every downstream decision is wrong. Fix: cycle counts every 2 weeks.',
      'Mistake 2: Overstocking dead SKUs. 20% of SKUs generate 80% of revenue. Trim the tail ruthlessly.',
      'Mistake 3: No reorder logic. Manual purchases lead to stock-outs and over-orders. Fix: AI-driven reorder points.',
      'Mistake 4: Ignoring seasonality. Diwali sales patterns don’t match summer patterns. Fix: 12-month rolling forecasts.',
      'Mistake 5: One-warehouse thinking in a multi-branch world. Fix: real-time stock visibility across all branches.',
      'Mistake 6: Not tracking shrinkage. If you don’t measure it, you’re losing 1–3% of revenue silently.',
      'Mistake 7: Manual GST reconciliation. Automate or spend a week every quarter chasing invoice mismatches.',
      'Fix these 7 and your net margin will move 200–400 basis points — without selling a single extra unit.',
    ],
    key: 'retail_inventory',
  },
  {
    slug: 'hrms-payroll-automation',
    title: 'HRMS + Payroll Automation: The Underrated Growth Lever',
    excerpt: 'Most founders think of HRMS as a compliance tool. It’s actually one of the highest-leverage investments you can make in your first 100 employees.',
    image: 'https://images.unsplash.com/photo-1619506147448-b56ba8ee11d7',
    category: 'HR & People',
    tags: ['HRMS', 'Payroll', 'HR Tech'],
    author: 'Ananya Iyer',
    role: 'Customer Success Head',
    date: '2026-04-22',
    readMin: 5,
    content: [
      'When founders talk about growth investments, HRMS rarely makes the list. It’s seen as a boring compliance tool. That’s a mistake.',
      'A modern HRMS is a growth multiplier because it removes friction from three critical workflows: (1) hiring, (2) attendance and (3) payroll. Each hour saved compounds.',
      'Case in point: a 60-person manufacturing client saved 34 hours per month on payroll processing alone. That’s 4 full days a month — for their HR head to focus on training and retention.',
      'Face-recognition attendance eliminates buddy-punching (typical shrinkage: 3–5% of payroll). PF/ESI automation prevents ₹1.5–5 lakh in penalties per year. Self-service leaves reduce manager time by 60%.',
      'The ROI math on a good HRMS is honestly embarrassing. Most clients recover the annual cost in the first month. If you have more than 25 employees and you’re still on Excel + WhatsApp for HR, you’re leaving hours and rupees on the table every day.',
    ],
    key: 'hrms_growth',
  },
  {
    slug: 'aws-cloud-migration-playbook',
    title: 'The 4-Week AWS Cloud Migration Playbook for Growing SaaS Teams',
    excerpt: 'From shared hosting to production AWS in 4 weeks — without downtime. The battle-tested playbook our DevOps team uses.',
    image: 'https://images.pexels.com/photos/6248959/pexels-photo-6248959.jpeg',
    category: 'Cloud & DevOps',
    tags: ['AWS', 'DevOps', 'Cloud Migration'],
    author: 'Rohan Shah',
    role: 'VP Engineering',
    date: '2026-04-15',
    readMin: 8,
    content: [
      'Every growing SaaS company hits a wall with shared hosting eventually. Slow queries, random downtime, no scalability. The next step — AWS — feels overwhelming. It shouldn’t be.',
      'Week 1: Assessment. Map your current stack, identify dependencies and set up an AWS account with proper IAM. Bill under ₹5,000 this week.',
      'Week 2: Foundation. VPC, subnets, security groups, RDS, S3, CloudFront, ACM. Everything infrastructure-as-code via Terraform.',
      'Week 3: Migration. Deploy application to ECS Fargate or App Runner. Run in parallel with existing production. Point 5% of traffic. Monitor closely.',
      'Week 4: Cutover. Gradually shift traffic 25% → 50% → 100% over 3 days. DNS TTL trick keeps rollback under 60 seconds.',
      'The results: 99.99% uptime, sub-200ms response times, ability to scale from 10 to 10,000 users overnight, and cost that’s often lower than the old provider (thanks to right-sizing).',
      'Skip the multi-month enterprise migration nightmare. In 4 focused weeks, you can be on world-class infrastructure.',
    ],
    key: 'aws_migration',
  },
  {
    slug: 'business-analytics-decisions',
    title: 'Why Most Business Dashboards Are Useless — And How to Build Ones That Aren’t',
    excerpt: 'Every executive has 12 dashboards. Almost none of them make a single decision faster. Here’s how to fix that.',
    image: 'https://images.pexels.com/photos/7693218/pexels-photo-7693218.jpeg',
    category: 'Data & Analytics',
    tags: ['Analytics', 'BI', 'Dashboards'],
    author: 'Vikram Rao',
    role: 'AI Lead',
    date: '2026-04-08',
    readMin: 6,
    content: [
      'Every CEO I meet has 12 dashboards. Sales, marketing, finance, ops, HR, product. Beautiful charts. Real-time data. And almost none of them help make a single decision faster.',
      'The problem is not the tools. Power BI, Tableau and Metabase are amazing. The problem is that most dashboards answer questions no one is asking.',
      'A useful dashboard answers three questions: (1) What matters this week? (2) What’s trending up or down? (3) What do I need to do about it?',
      'That’s it. Not 40 KPIs. Not a rainbow of colors. Three questions, cleanly answered.',
      'The best dashboard we ever built has 4 numbers. Weekly revenue, weekly leads, CSAT, and one strategic metric that changes quarterly. It gets opened by 47 people every Monday morning.',
      'Before you build another dashboard, ask: what decision does this help make? If you can’t answer in one sentence, you’re building a graveyard, not an instrument.',
    ],
    key: 'dashboards_useless',
  },
  {
    slug: 'startup-mvp-building-tips',
    title: 'How We Build MVPs in 6 Weeks (And Ship Them to Real Users)',
    excerpt: 'Six weeks. From idea to paying customer. The exact stack, process and mindset our team uses for 40+ startup MVPs.',
    image: 'https://images.unsplash.com/photo-1549477614-0a053f6ab768',
    category: 'Startups',
    tags: ['MVP', 'Startup', 'Product'],
    author: 'Aarav Mehta',
    role: 'Founder & CEO',
    date: '2026-04-01',
    readMin: 7,
    content: [
      'Six weeks. That’s our default timeline for a startup MVP. Idea to paying customer. It’s not magic — it’s a repeatable process we’ve run 40+ times.',
      'Week 1: The kill-features workshop. We take the founder’s wishlist of 30 features and kill 25. Only 5 make it to v1. This is the single hardest part.',
      'Week 2: Interactive prototype. Figma clickable, real content, feels like a shipped app. If users don’t “get it” in 30 seconds, we redesign.',
      'Weeks 3–5: Build. React Native + Node + MongoDB. Daily standups. Weekly demos to the founder. Half the code is written in the first week.',
      'Week 6: Launch. Deploy to production. Onboard first 10 users personally. Fix the top 3 bugs live. Charge money.',
      'The trick is not writing code fast. It’s deciding what NOT to build. If your MVP has more than 5 features, you’re not building an MVP — you’re building a product.',
      'Ship in weeks. Learn in weeks. Iterate in weeks. That’s how startups win.',
    ],
    key: 'mvp_playbook',
  },
]

export function getPostBySlug(slug) {
  return BLOG_POSTS.find(p => p.slug === slug)
}

export function getRelatedPosts(slug, count = 3) {
  const post = getPostBySlug(slug)
  if (!post) return []
  return BLOG_POSTS.filter(p => p.slug !== slug && p.category === post.category).slice(0, count).length >= count
    ? BLOG_POSTS.filter(p => p.slug !== slug && p.category === post.category).slice(0, count)
    : BLOG_POSTS.filter(p => p.slug !== slug).slice(0, count)
}
