// 12 Industries with unique content and illustration keys
export const INDUSTRY_LIST = [
  {
    slug: 'manufacturing',
    name: 'Manufacturing',
    illustration: 'manufacturing',
    tagline: 'Digitize the shop floor. Ship on time. Every time.',
    heroSubtitle: 'From BOM and MRP to work orders, QC and dispatch — unify your factory on one live dashboard.',
    overview: 'Manufacturers lose 20–30% of margins to spreadsheets, silos and missed production plans. Olive Orange gives your plant a single live view — raw materials, work-in-progress, quality, dispatch — so every decision is data-driven.',
    painPoints: [
      'Excel-based production planning that breaks weekly',
      'No real-time WIP or machine utilization visibility',
      'Delayed dispatches and angry customers',
      'QC issues discovered too late',
    ],
    solutions: [
      { title: 'Olive Manufacturing ERP', desc: 'BOM, MRP, work orders, batch tracking, QC — end-to-end.', link: '/services/industry-software' },
      { title: 'IoT + Analytics Dashboards', desc: 'Machine data → real-time OEE and downtime alerts.', link: '/services/data-analytics-bi' },
      { title: 'Automation & RPA', desc: 'Auto-generate PO, invoices, dispatch docs.', link: '/services/automation-solutions' },
    ],
    metrics: [
      { v: '35%', l: 'Reduction in production delays' },
      { v: '4x', l: 'Faster monthly closing' },
      { v: '₹1.2Cr', l: 'Avg annual savings (mid-size plant)' },
    ],
    caseStudy: {
      client: 'Shah Textiles',
      quote: 'Olive Manufacturing ERP replaced 6 Excel files and 2 legacy tools. Closing time went from 5 days to 6 hours.',
      role: 'Priya Shah, MD',
    },
    recommended: ['industry-software', 'data-analytics-bi', 'automation-solutions'],
  },
  {
    slug: 'healthcare',
    name: 'Healthcare',
    illustration: 'healthcare',
    tagline: 'Cure the paperwork. Focus on the patient.',
    heroSubtitle: 'HIPAA-friendly hospital ERP + patient app + AI triage — for clinics, diagnostics and multi-specialty hospitals.',
    overview: 'From OPD registration and billing to pharmacy, IPD, lab and pathology reports — our Hospital ERP runs the whole facility. Add AI chatbots for appointments and voice assistants for elderly patients.',
    painPoints: [
      'Long OPD queues and manual billing',
      'Paper prescriptions and lost patient history',
      'Pharmacy stock-outs of critical medicines',
      'No unified view across departments',
    ],
    solutions: [
      { title: 'Olive Hospital ERP', desc: 'OPD, IPD, pharmacy, lab and billing — one system.', link: '/services/industry-software' },
      { title: 'AI Chatbot + Voice', desc: '24×7 appointment booking in Hindi and English.', link: '/services/ai-solutions' },
      { title: 'Patient Mobile App', desc: 'Reports, prescriptions and follow-ups on the phone.', link: '/services/mobile-app-development' },
    ],
    metrics: [
      { v: '60%', l: 'Shorter OPD wait times' },
      { v: '90%', l: 'Digital patient records' },
      { v: '4.7⭐', l: 'Average patient satisfaction' },
    ],
    caseStudy: {
      client: 'CareWell Hospital',
      quote: 'OPD queues vanished. Patient satisfaction is at an all-time high.',
      role: 'Dr. Meera Iyer, Director',
    },
    recommended: ['industry-software', 'ai-solutions', 'mobile-app-development'],
  },
  {
    slug: 'education',
    name: 'Education',
    illustration: 'education',
    tagline: 'Run schools like modern SaaS companies.',
    heroSubtitle: 'School ERP + parent app + admissions CRM — tailored for K-12, coaching institutes and colleges.',
    overview: 'Manage admissions, fees, attendance, exams, timetable, transport, hostel and parent communication from one platform. Add a parent app so families never miss an update.',
    painPoints: [
      'Fee collection nightmares at term start',
      'Manual attendance and lost registers',
      'Parents chasing teachers for updates',
      'No visibility into student performance trends',
    ],
    solutions: [
      { title: 'Olive School ERP', desc: 'Admissions, fees, attendance, exams, transport.', link: '/services/industry-software' },
      { title: 'Parent + Student App', desc: 'Real-time updates, homework, fee payment.', link: '/services/mobile-app-development' },
      { title: 'Analytics Dashboards', desc: 'Student performance and enrolment insights.', link: '/services/data-analytics-bi' },
    ],
    metrics: [
      { v: '92%', l: 'On-time fee collection' },
      { v: '3x', l: 'Faster admission processing' },
      { v: '85%', l: 'Parent app adoption' },
    ],
    caseStudy: {
      client: 'Sunrise International School',
      quote: 'Fee collection at term-start is now a 2-hour job, not a 2-week crisis.',
      role: 'Anita Menon, Principal',
    },
    recommended: ['industry-software', 'mobile-app-development', 'automation-solutions'],
  },
  {
    slug: 'retail',
    name: 'Retail',
    illustration: 'retail',
    tagline: 'Turn footfall into loyalty. Every visit, every store.',
    heroSubtitle: 'POS + inventory + loyalty + omnichannel — built for single stores and 1000+ outlet chains.',
    overview: 'Sell across POS, website and marketplaces with one live inventory. Reward repeat customers with a built-in loyalty engine, and let AI predict what to stock, where.',
    painPoints: [
      'Stock discrepancies across branches',
      'Slow billing during peak hours',
      'No idea who your best customers are',
      'Manual GST reconciliation',
    ],
    solutions: [
      { title: 'Olive POS + Inventory', desc: 'Lightning-fast billing with real-time stock.', link: '/services/industry-software' },
      { title: 'Customer Loyalty App', desc: 'Points, coupons and personalized offers.', link: '/services/mobile-app-development' },
      { title: 'AI Recommendations', desc: 'Predict demand, optimize assortment.', link: '/services/ai-solutions' },
    ],
    metrics: [
      { v: '2.4x', l: 'Faster checkout' },
      { v: '38%', l: 'Increase in repeat customers' },
      { v: '99.9%', l: 'Stock accuracy' },
    ],
    caseStudy: {
      client: 'Urban Kart',
      quote: 'From 3 stores on WhatsApp to 24 stores on one live system in 8 months.',
      role: 'Kunal Mehra, Founder',
    },
    recommended: ['industry-software', 'ai-solutions', 'digital-marketing'],
  },
  {
    slug: 'restaurant',
    name: 'Restaurant',
    illustration: 'restaurant',
    tagline: 'From table 12 to Zomato. One screen. Zero chaos.',
    heroSubtitle: 'Restaurant POS + KOT + delivery integrations + captain app — for QSR, cafes and fine-dine chains.',
    overview: 'Take orders on any device, print KOTs to any station, sync with Zomato/Swiggy, manage inventory and see live P&L by outlet. Grow revenue without growing chaos.',
    painPoints: [
      'Missed online orders during peak hours',
      'KOTs lost between tables and kitchen',
      'No idea which items make real money',
      'Manual reconciliation with aggregators',
    ],
    solutions: [
      { title: 'Olive Restaurant POS', desc: 'Multi-device POS with KOT and captain app.', link: '/services/industry-software' },
      { title: 'Aggregator Sync', desc: 'Zomato, Swiggy, ONDC — auto-accept and reconcile.', link: '/services/automation-solutions' },
      { title: 'Menu + P&L Analytics', desc: 'See which dishes drive profit, per outlet.', link: '/services/data-analytics-bi' },
    ],
    metrics: [
      { v: '40%', l: 'Higher waiter productivity' },
      { v: '₹8L+', l: 'Recovered from aggregator gaps (avg)' },
      { v: '15%', l: 'Menu margin lift' },
    ],
    caseStudy: {
      client: 'KrunchBox F&B',
      quote: 'POS + KOT + delivery on one screen — waiter productivity up 40%.',
      role: 'Sameer Kapoor, CEO',
    },
    recommended: ['industry-software', 'automation-solutions', 'data-analytics-bi'],
  },
  {
    slug: 'real-estate',
    name: 'Real Estate',
    illustration: 'realestate',
    tagline: 'From site visit to registration — track every rupee.',
    heroSubtitle: 'Real Estate CRM + broker network + EMI tracker — for builders, brokers and property portals.',
    overview: 'Manage leads across projects, run WhatsApp campaigns, track site visits, generate quotations, book units, follow EMIs and reward your broker network — all in one system built for Indian real estate.',
    painPoints: [
      'Leads leaking across channels',
      'Site-visit-to-booking ratio is a mystery',
      'Broker commissions calculated in Excel',
      'EMI follow-ups falling behind',
    ],
    solutions: [
      { title: 'Olive Real Estate CRM', desc: 'Lead → site visit → booking → registration.', link: '/services/industry-software' },
      { title: 'WhatsApp Automation', desc: 'Broadcast, follow-up and book demos on WA.', link: '/services/automation-solutions' },
      { title: 'EMI + Payment Tracker', desc: 'Auto-reminders + collections dashboard.', link: '/services/business-ecosystem' },
    ],
    metrics: [
      { v: '2x', l: 'Site-visit to booking ratio' },
      { v: '48%', l: 'Faster deal closure' },
      { v: '100%', l: 'Broker commission accuracy' },
    ],
    caseStudy: {
      client: 'Verma Realty',
      quote: 'The Real Estate CRM is a masterpiece. Our site-visit-to-booking ratio doubled.',
      role: 'Rahul Verma, Founder',
    },
    recommended: ['industry-software', 'automation-solutions', 'digital-marketing'],
  },
  {
    slug: 'finance',
    name: 'Finance',
    illustration: 'finance',
    tagline: 'Compliant. Automated. Auditor-friendly.',
    heroSubtitle: 'Accounting, lending CRM, KYC automation and BI dashboards — for NBFCs, DSAs and CA firms.',
    overview: 'Automate KYC, disbursals, EMI collections and portfolio reporting. Give auditors the reports they need with one click. Detect fraud with AI models trained on your data.',
    painPoints: [
      'Manual KYC that takes days',
      'Portfolio reports lag by weeks',
      'No fraud detection layer',
      'Compliance filings done at the last minute',
    ],
    solutions: [
      { title: 'KYC + Doc Processing AI', desc: 'OCR + verification in under 2 minutes.', link: '/services/ai-solutions' },
      { title: 'Lending CRM', desc: 'Applications, underwriting, disbursal, EMI.', link: '/services/industry-software' },
      { title: 'BI + Compliance Dashboards', desc: 'RBI-ready reports at one click.', link: '/services/data-analytics-bi' },
    ],
    metrics: [
      { v: '<2 min', l: 'KYC processing time' },
      { v: '99.5%', l: 'Automated compliance filings' },
      { v: '₹3.5Cr', l: 'Avg fraud prevented per year' },
    ],
    caseStudy: {
      client: 'Prime Capital NBFC',
      quote: 'Our KYC went from 3 days to 2 minutes. Loan-book grew 40% without adding ops staff.',
      role: 'Vikram Rao, COO',
    },
    recommended: ['ai-solutions', 'industry-software', 'data-analytics-bi'],
  },
  {
    slug: 'construction',
    name: 'Construction',
    illustration: 'construction',
    tagline: 'Bring the site to your dashboard. In real time.',
    heroSubtitle: 'Project management, material tracking, labour attendance, safety and BOQ — for developers and contractors.',
    overview: 'Track every project from foundation to finishing. Monitor material inflow, labour attendance, subcontractor billing, safety incidents and budget burn — all on one dashboard, all on mobile.',
    painPoints: [
      'Material pilferage at sites',
      'Labour attendance via paper registers',
      'Subcontractor bills submitted without proof',
      'Project delays hidden till too late',
    ],
    solutions: [
      { title: 'Construction Project ERP', desc: 'Gantt, BOQ, RA bills, material issue.', link: '/services/industry-software' },
      { title: 'Site Mobile App', desc: 'Labour attendance, photos, safety, GPS.', link: '/services/mobile-app-development' },
      { title: 'Material + Budget BI', desc: 'Live burn-rate vs BOQ per site.', link: '/services/data-analytics-bi' },
    ],
    metrics: [
      { v: '18%', l: 'Reduction in material pilferage' },
      { v: '30%', l: 'Fewer project delays' },
      { v: '100%', l: 'Digital labour attendance' },
    ],
    caseStudy: {
      client: 'BuildRight Infra',
      quote: 'Suddenly I know exactly what is happening on 14 sites, from my phone.',
      role: 'Nikhil Desai, MD',
    },
    recommended: ['industry-software', 'mobile-app-development', 'data-analytics-bi'],
  },
  {
    slug: 'textile',
    name: 'Textile',
    illustration: 'textile',
    tagline: 'From yarn to invoice. Trace every meter.',
    heroSubtitle: 'Weaving, dyeing, processing and garment ERP + trader CRM — built for Surat, Ludhiana, Tirupur ecosystems.',
    overview: 'Track lots, batches and shades from raw yarn to finished packing lists. Automate broker payouts, LR generation, GST and e-way bills. Sell to global buyers with a modern trader portal.',
    painPoints: [
      'Lot & shade tracking on paper cards',
      'Broker commission chaos',
      'Manual GST & e-way bills',
      'No sample-to-order tracking',
    ],
    solutions: [
      { title: 'Textile ERP', desc: 'Weaving, dyeing, processing, garment.', link: '/services/industry-software' },
      { title: 'Trader Portal + WA', desc: 'Send catalogs, receive orders on WhatsApp.', link: '/services/automation-solutions' },
      { title: 'Billing + GST Automation', desc: 'One-click invoices, LR, e-way bills.', link: '/services/business-ecosystem' },
    ],
    metrics: [
      { v: '100%', l: 'Lot-level traceability' },
      { v: '₹2L+', l: 'Saved per month in broker leakage' },
      { v: '10x', l: 'Faster e-way bill generation' },
    ],
    caseStudy: {
      client: 'Radhe Fabrics (Surat)',
      quote: 'We track every meter of fabric from loom to buyer — something we never imagined possible.',
      role: 'Jignesh Patel, Partner',
    },
    recommended: ['industry-software', 'automation-solutions', 'business-ecosystem'],
  },
  {
    slug: 'logistics',
    name: 'Logistics',
    illustration: 'logistics',
    tagline: 'On-time. On-route. On-brand.',
    heroSubtitle: 'TMS, fleet tracking, driver app, POD and last-mile — for 3PL, LTL and D2C logistics teams.',
    overview: 'Optimize routes with AI, dispatch trips with one click, track vehicles live, capture proof-of-delivery on driver app and share ETAs with customers on WhatsApp — automatically.',
    painPoints: [
      'Manual route planning wastes fuel',
      'Customers keep asking “where is my order?”',
      'Paper PODs get lost',
      'Freight billing has 15–25% leakage',
    ],
    solutions: [
      { title: 'Transport Mgmt System (TMS)', desc: 'Trips, indents, freight billing, ledger.', link: '/services/industry-software' },
      { title: 'AI Route Optimization', desc: 'Cut km + fuel by 12–20%.', link: '/services/ai-solutions' },
      { title: 'Driver + Customer App', desc: 'POD, ePOD, live ETA on WhatsApp.', link: '/services/mobile-app-development' },
    ],
    metrics: [
      { v: '18%', l: 'Fuel cost reduction' },
      { v: '95%', l: 'On-time deliveries' },
      { v: '100%', l: 'Digital POD' },
    ],
    caseStudy: {
      client: 'FastLine 3PL',
      quote: 'Route AI + driver app cut our diesel bill by ₹6 lakh per month.',
      role: 'Ramesh Iyer, Operations Head',
    },
    recommended: ['industry-software', 'ai-solutions', 'mobile-app-development'],
  },
  {
    slug: 'service-businesses',
    name: 'Service Businesses',
    illustration: 'services',
    tagline: 'Book. Serve. Delight. Repeat.',
    heroSubtitle: 'Field service management + booking app + AMC tracker — for salons, home services, ACs, repairs and clinics.',
    overview: 'Let customers book online, dispatch the right technician, capture job cards on mobile, collect payments and get 5-star reviews — all on a system that’s ready in days.',
    painPoints: [
      'Booking chaos on WhatsApp and calls',
      'Technicians’ job cards on paper',
      'AMC renewals slipping through cracks',
      'No customer feedback loop',
    ],
    solutions: [
      { title: 'Field Service Suite', desc: 'Bookings, dispatch, job card, invoicing.', link: '/services/industry-software' },
      { title: 'Customer Booking App', desc: 'iOS + Android + web widget.', link: '/services/mobile-app-development' },
      { title: 'AMC Automation', desc: 'Auto-renew reminders + WA nudges.', link: '/services/automation-solutions' },
    ],
    metrics: [
      { v: '3.2x', l: 'More bookings' },
      { v: '92%', l: 'AMC renewal rate' },
      { v: '4.8⭐', l: 'Average customer rating' },
    ],
    caseStudy: {
      client: 'CoolCare AC Services',
      quote: 'From 40 to 180 bookings a day — same team, better system.',
      role: 'Rajat Bansal, Founder',
    },
    recommended: ['industry-software', 'mobile-app-development', 'automation-solutions'],
  },
  {
    slug: 'startups',
    name: 'Startups',
    illustration: 'startups',
    tagline: 'Move at startup speed. With enterprise-grade software.',
    heroSubtitle: 'MVP dev, growth marketing, CRM setup and investor-ready dashboards — all under one roof.',
    overview: 'From ideation to Series A, we act as your technology partner: build the MVP, set up CRM + finance stack, run performance marketing, and prepare investor-ready dashboards — so founders can focus on selling and hiring.',
    painPoints: [
      'MVP delayed by unreliable dev shops',
      'No CRM — leads managed in inbox',
      'Marketing spend not producing pipeline',
      'Board updates take a week each month',
    ],
    solutions: [
      { title: 'MVP in 6 Weeks', desc: 'React Native / Flutter + backend + hosting.', link: '/services/mobile-app-development' },
      { title: 'Startup Growth Stack', desc: 'CRM + Ads + Automation + Analytics.', link: '/services/digital-marketing' },
      { title: 'Fractional CTO', desc: 'Senior engineering leadership on retainer.', link: '/services/business-consulting' },
    ],
    metrics: [
      { v: '6 wks', l: 'To first paying customer' },
      { v: '3x', l: 'Faster fund-raise-ready decks' },
      { v: '40+', l: 'Startups partnered with' },
    ],
    caseStudy: {
      client: 'Zentek (Seed Stage SaaS)',
      quote: 'MVP in 6 weeks, first ARR in month 3. Olive Orange is our tech co-founder.',
      role: 'Aditi Rao, CEO',
    },
    recommended: ['mobile-app-development', 'digital-marketing', 'business-consulting'],
  },
]

export function getIndustryBySlug(slug) {
  return INDUSTRY_LIST.find(i => i.slug === slug)
}
