// 15 Products (Oli branding) with SaaS dashboard images
export const PRODUCTS = [
  {
    slug: 'oli-crm',
    name: 'Oli CRM',
    tag: 'Sales & Marketing',
    tagline: 'Close deals 3× faster with an AI-powered pipeline.',
    heroSubtitle: 'Turn every website visitor, WhatsApp chat and phone call into a customer with the smartest CRM in India.',
    image: 'https://images.unsplash.com/photo-1648134859177-525771773915',
    overview: 'Oli CRM captures leads from your website, WhatsApp, Facebook, IndiaMART and phone calls automatically — then guides your sales team through every follow-up with AI nudges. See every deal, every rupee, every conversation in one place.',
    features: ['Multi-channel lead capture (Web + WA + FB + IndiaMART)', 'AI follow-up reminders and auto-drip campaigns', 'Visual sales pipeline with drag-and-drop', 'Quotation, invoice and payment tracking', 'Sales team performance leaderboards', 'Mobile app for field sales', 'WhatsApp Business API integration', 'GST-ready invoicing'],
    industries: ['Manufacturing', 'Real Estate', 'Retail', 'Startups', 'Service Businesses'],
    pricing: { mrp: 24999, offer: 14999, note: 'Per year / 5 users' },
  },
  {
    slug: 'oli-erp',
    name: 'Oli ERP',
    tag: 'Operations',
    tagline: 'One platform to run finance, purchase, sales and operations.',
    heroSubtitle: 'Replace 6+ tools with one integrated ERP built for Indian mid-sized businesses.',
    image: 'https://images.unsplash.com/photo-1648134859187-71dadc9f815a',
    overview: 'Oli ERP unifies your finance, purchase, sales, inventory and operations into one connected system. Live P&L, real-time stock, purchase-to-pay, order-to-cash — all with GST, TDS and audit-ready reports out of the box.',
    features: ['Finance + GST + TDS automation', 'Purchase-to-pay workflow', 'Sales order to invoice + collections', 'Multi-branch and multi-warehouse', 'Real-time P&L and balance sheet', 'Approval workflows on mobile', 'Tally / Zoho / bank integrations', 'Custom dashboards per role'],
    industries: ['Manufacturing', 'Textile', 'Retail', 'Logistics', 'Construction'],
    pricing: { mrp: 89999, offer: 59999, note: 'Per year / 25 users' },
  },
  {
    slug: 'oli-hrms',
    name: 'Oli HRMS',
    tag: 'People',
    tagline: 'Attendance, payroll and performance — fully automated.',
    heroSubtitle: 'The complete HR platform — from face-recognition attendance to one-click payroll and PF/ESI compliance.',
    image: 'https://images.unsplash.com/photo-1648134859196-3aa762e9440d',
    overview: 'Oli HRMS runs the entire employee lifecycle — attendance (face/biometric/geo), leave, payroll, PF/ESI/PT, performance reviews, expense claims and offboarding — with employee and manager apps included.',
    features: ['Face + biometric + GPS attendance', 'One-click payroll with PF/ESI/PT/TDS', 'Leave and holiday management', 'Employee self-service mobile app', 'Performance reviews and goals (OKRs)', 'Expense claims and reimbursements', 'Digital offer letters and offboarding', 'Statutory reports for auditors'],
    industries: ['Manufacturing', 'Retail', 'Healthcare', 'Education', 'Service Businesses'],
    pricing: { mrp: 49999, offer: 29999, note: 'Per year / 50 employees' },
  },
  {
    slug: 'oli-pos',
    name: 'Oli POS',
    tag: 'Retail',
    tagline: 'Lightning-fast billing with real-time inventory sync.',
    heroSubtitle: 'The modern POS for retail chains — works offline, syncs online, supports 100+ printers, weighing scales and payment devices.',
    image: 'https://images.unsplash.com/photo-1560461396-ec0ef7bb29dd',
    overview: 'Oli POS powers single stores and 1000+ outlet chains. Sell across POS, website, marketplaces and WhatsApp with one live inventory. Loyalty engine, offers, discounts and GST reports — all built in.',
    features: ['Offline-first billing (never lose a sale)', 'Barcode + weighing scale support', 'Multi-branch stock transfer', 'Loyalty, coupons and offers', 'GST invoices + e-way bill', 'UPI, cards, wallets — all payments', 'Customer app with rewards', 'Manager mobile dashboard'],
    industries: ['Retail', 'Restaurant', 'Textile', 'Manufacturing'],
    pricing: { mrp: 19999, offer: 11999, note: 'Per year / per terminal' },
  },
  {
    slug: 'oli-billing',
    name: 'Oli Billing',
    tag: 'Finance',
    tagline: 'GST-ready invoices, e-way bills and quotations in seconds.',
    heroSubtitle: 'The simplest billing software for Indian businesses — with WhatsApp send, payment links and auto-reminders.',
    image: 'https://images.unsplash.com/photo-1660970781103-ba6749cb9ce3',
    overview: 'Oli Billing generates GST-compliant invoices, e-way bills, quotations, delivery challans and receipts — all in seconds. Share via WhatsApp, embed UPI payment links, and get paid faster with automated reminders.',
    features: ['GST invoices + e-way bills + e-invoicing', 'WhatsApp send with 1 click', 'UPI payment links inside invoices', 'Auto payment reminders', 'Quotations → orders → invoices', 'Delivery challans + receipts', 'Multi-company + multi-branch', 'Tally / Zoho export'],
    industries: ['Retail', 'Service Businesses', 'Textile', 'Manufacturing', 'Startups'],
    pricing: { mrp: 9999, offer: 5999, note: 'Per year / unlimited invoices' },
  },
  {
    slug: 'oli-school-erp',
    name: 'Oli School ERP',
    tag: 'Education',
    tagline: 'One platform for admissions, fees, exams and parent app.',
    heroSubtitle: 'Purpose-built for K-12, coaching institutes and colleges. Loved by principals, teachers and parents.',
    image: 'https://images.unsplash.com/photo-1589859509530-1bef96699d28',
    overview: 'Oli School ERP runs admissions, fees, attendance, exams, timetable, transport, hostel and library. Parent + student mobile apps keep families in the loop — fee payments, homework, marks, everything.',
    features: ['Online admissions with document upload', 'Fee collection with UPI links', 'Attendance (biometric/RFID/geo)', 'Exam management + report cards', 'Timetable, transport, hostel, library', 'Parent + student mobile app', 'SMS + WhatsApp + email alerts', 'Principal analytics dashboard'],
    industries: ['Education'],
    pricing: { mrp: 49999, offer: 24999, note: 'Per year / school' },
  },
  {
    slug: 'oli-hospital-erp',
    name: 'Oli Hospital ERP',
    tag: 'Healthcare',
    tagline: 'OPD, IPD, pharmacy, lab and billing — one system.',
    heroSubtitle: 'Everything a modern hospital needs: patient journey, doctors, pharmacy, lab, insurance and billing.',
    image: 'https://images.unsplash.com/photo-1590658094082-88f4c5814ea1',
    overview: 'Oli Hospital ERP digitizes the full patient journey — registration, appointments, OPD/IPD, pharmacy dispensing, lab reports, insurance TPA, billing and NABH-friendly reports. Add patient app for prescriptions and follow-ups.',
    features: ['OPD + IPD + ICU management', 'Doctor consultation with e-prescriptions', 'Pharmacy with batch/expiry tracking', 'Lab with test reports (PDF+WhatsApp)', 'Insurance / TPA claim processing', 'Room / bed management', 'Patient mobile app + digital records', 'NABH-ready audit reports'],
    industries: ['Healthcare'],
    pricing: { mrp: 99999, offer: 49999, note: 'Per year / hospital' },
  },
  {
    slug: 'oli-manufacturing-erp',
    name: 'Oli Manufacturing ERP',
    tag: 'Factory',
    tagline: 'BOM, MRP, work orders and QC — for the smart shop floor.',
    heroSubtitle: 'The complete ERP for Indian manufacturers — discrete, process and batch production with QC and traceability.',
    image: 'https://images.unsplash.com/photo-1598929440176-7eeb8b1a6cc5',
    overview: 'Oli Manufacturing ERP handles BOM, MRP, work orders, sub-contracting, QC, batch/serial tracking, machine utilization and dispatch. Live P&L, WIP dashboard and OEE analytics on your mobile.',
    features: ['Multi-level BOM + MRP planning', 'Work orders + subcontracting', 'Batch and serial number tracking', 'Quality inspection at every stage', 'Machine OEE and downtime tracking', 'Material issue and return', 'Costing (actual vs standard)', 'Live dashboards on mobile'],
    industries: ['Manufacturing', 'Textile'],
    pricing: { mrp: 149000, offer: 89000, note: 'Per year / plant' },
  },
  {
    slug: 'oli-inventory',
    name: 'Oli Inventory',
    tag: 'Warehouse',
    tagline: 'Real-time stock across branches, warehouses and POS.',
    heroSubtitle: 'The inventory OS — barcodes, batches, expiry, multi-branch transfers and reorder AI.',
    image: 'https://images.unsplash.com/photo-1573868056472-22834cad367c',
    overview: 'Oli Inventory tracks every SKU across every location in real time. Handle barcodes, serial numbers, batches, expiry dates, multi-unit conversions and inter-branch transfers effortlessly. AI predicts reorder points.',
    features: ['Multi-warehouse + multi-branch stock', 'Barcode + serial + batch tracking', 'Expiry date alerts', 'AI reorder point suggestions', 'Physical stock audit with mobile app', 'Purchase order + GRN', 'Stock valuation (FIFO/LIFO/Avg)', 'Real-time stock ledger'],
    industries: ['Retail', 'Manufacturing', 'Textile', 'Logistics'],
    pricing: { mrp: 29999, offer: 17999, note: 'Per year / branch' },
  },
  {
    slug: 'oli-project-management',
    name: 'Oli Project Management',
    tag: 'Teams',
    tagline: 'Tasks, sprints, time-tracking and Gantt — for hybrid teams.',
    heroSubtitle: 'The Asana-meets-Jira for growing teams. Kanban, Gantt, timesheets and client portals in one place.',
    image: 'https://images.unsplash.com/photo-1573867607131-872f83689352',
    overview: 'Oli Project Management gives your team a home for every task, sprint and deadline. Visual Kanban boards, powerful Gantt charts, built-in timesheets and client portals — all in one clean, fast interface.',
    features: ['Kanban + list + calendar + Gantt views', 'Sprints, story points, burndown', 'Timesheets + billable hours', 'Client access portal', 'Automations (“if this then that”)', 'Comments, mentions, attachments', 'Mobile apps for iOS + Android', 'Reports on team velocity'],
    industries: ['Startups', 'Service Businesses', 'Construction'],
    pricing: { mrp: 14999, offer: 8999, note: 'Per year / 20 users' },
  },
  {
    slug: 'oli-service-desk',
    name: 'Oli Service Desk',
    tag: 'Support',
    tagline: 'Tickets, SLA, WhatsApp and chat — all in one helpdesk.',
    heroSubtitle: 'The customer support platform for teams that care. Omnichannel ticketing with SLAs, escalations and CSAT.',
    image: 'https://images.pexels.com/photos/6248959/pexels-photo-6248959.jpeg',
    overview: 'Oli Service Desk unifies tickets from email, WhatsApp, chat, phone and social into one queue. SLA rules, auto-assignment, escalations, CSAT surveys and rich reports — everything you need to delight customers at scale.',
    features: ['Email + WhatsApp + chat + phone in one queue', 'SLA rules + auto-escalation', 'Canned responses + knowledge base', 'Customer self-service portal', 'CSAT and NPS surveys', 'Agent performance dashboards', 'Round-robin assignment', 'API to sync with CRM/ERP'],
    industries: ['Service Businesses', 'Retail', 'Healthcare', 'Real Estate'],
    pricing: { mrp: 19999, offer: 11999, note: 'Per year / 10 agents' },
  },
  {
    slug: 'oli-visitor-management',
    name: 'Oli Visitor Management',
    tag: 'Front Desk',
    tagline: 'Modern gate-pass with photos, OTPs and host alerts.',
    heroSubtitle: 'Give visitors a 5-star first impression. Tablet-based check-in with photo, ID scan and OTP-based host approval.',
    image: 'https://images.pexels.com/photos/8204311/pexels-photo-8204311.jpeg',
    overview: 'Oli Visitor Management turns your front desk into a smart, secure and welcoming experience. Visitors self-check-in on a tablet, capture a photo, scan ID, and get an OTP-based host approval — all in under 30 seconds.',
    features: ['Tablet-based self check-in', 'Photo capture + ID scan (Aadhaar / PAN)', 'OTP-based host approval', 'Pre-book visitors + QR passes', 'Delivery / courier tracking', 'Emergency evacuation lists', 'Live front-desk dashboard', 'Integrates with access control'],
    industries: ['Manufacturing', 'Real Estate', 'Healthcare', 'Education'],
    pricing: { mrp: 24999, offer: 14999, note: 'Per year / location' },
  },
  {
    slug: 'oli-restaurant-pos',
    name: 'Oli Restaurant POS',
    tag: 'F&B',
    tagline: 'From table 12 to Zomato — one screen, zero chaos.',
    heroSubtitle: 'The restaurant OS — POS + KOT + captain app + delivery aggregator sync + live P&L.',
    image: 'https://images.pexels.com/photos/36747234/pexels-photo-36747234.jpeg',
    overview: 'Oli Restaurant POS runs QSRs, cafes, cloud kitchens and fine-dine chains. Take orders on any device, print KOTs to any station, sync with Zomato/Swiggy/ONDC and see live P&L by outlet.',
    features: ['Multi-device POS (tablet + desktop)', 'KOT printing to any station', 'Captain app for waiters', 'Zomato + Swiggy + ONDC sync', 'Table + reservation management', 'Loyalty + coupons + offers', 'Recipe + inventory linked', 'Live P&L by outlet'],
    industries: ['Restaurant'],
    pricing: { mrp: 29999, offer: 17999, note: 'Per year / outlet' },
  },
  {
    slug: 'oli-ai-assistant',
    name: 'Oli AI Assistant',
    tag: 'AI',
    tagline: 'Your in-house AI for reports, queries and automations.',
    heroSubtitle: 'Ask questions in plain English, Hindi or Gujarati. Get instant answers, charts and next actions.',
    image: 'https://images.pexels.com/photos/20694723/pexels-photo-20694723.jpeg',
    overview: 'Oli AI Assistant sits on top of your CRM, ERP and databases. Ask “show me top 10 customers this month” or “which stores are low on stock?” in plain language — get instant answers, charts and one-click actions.',
    features: ['Ask in English / Hindi / Gujarati', 'Natural language → SQL / API queries', 'Auto-generated charts and tables', 'One-click actions (send report, alert manager)', 'Runs on your own data, privately', 'Voice-ready (mic input)', 'WhatsApp and Slack bots included', 'Custom knowledge base'],
    industries: ['Manufacturing', 'Retail', 'Finance', 'Startups'],
    pricing: { mrp: 99999, offer: 59999, note: 'Per year / company' },
  },
  {
    slug: 'oli-real-estate-crm',
    name: 'Oli Real Estate CRM',
    tag: 'Realty',
    tagline: 'From site visit to registration — track every rupee.',
    heroSubtitle: 'Built for Indian builders, brokers and channel partners. WhatsApp campaigns, EMI tracker and broker payouts.',
    image: 'https://images.pexels.com/photos/36950633/pexels-photo-36950633.jpeg',
    overview: 'Oli Real Estate CRM manages leads across projects, runs WhatsApp broadcasts, tracks site visits, generates quotations, books units, follows EMIs and rewards your broker network — all in one system built specifically for Indian real estate.',
    features: ['Multi-project lead management', 'Site visit scheduling + follow-up', 'Quotation + booking + agreement', 'EMI tracker + payment reminders', 'Broker payout automation', 'WhatsApp Business API broadcast', 'RERA-ready compliance reports', 'Owner + broker mobile apps'],
    industries: ['Real Estate'],
    pricing: { mrp: 39999, offer: 24999, note: 'Per year / project' },
  },
]

export function getProductBySlug(slug) {
  return PRODUCTS.find(p => p.slug === slug)
}
