// Master data for all 12 service categories
export const SERVICE_CATEGORIES = [
  {
    slug: 'ai-solutions',
    name: 'AI Solutions',
    icon: 'Bot',
    tagline: 'Turn artificial intelligence into your unfair advantage.',
    heroSubtitle: 'From chatbots that never sleep to predictive models that see the future — we ship AI that actually moves your KPIs.',
    overview: 'We design, train and deploy production-grade AI systems tailored to your business. Whether you need a 24×7 sales chatbot, an OCR engine for invoices, or a recommendation system that lifts basket size, our AI stack is built on the latest LLMs, vector databases and MLOps pipelines. Every model we ship is measurable, explainable and cost-optimized.',
    benefits: [
      { title: '10× faster customer response', desc: 'AI agents handle 80% of queries instantly.' },
      { title: 'Cut manual work by 60%', desc: 'Automate document reading, tagging, and routing.' },
      { title: 'Higher conversion', desc: 'Personalized recommendations lift revenue 18–35%.' },
      { title: 'Enterprise-grade privacy', desc: 'Deploy on your cloud, your data never leaves.' },
    ],
    features: [
      { title: 'GPT / Claude / Gemini powered', desc: 'Choose the best model for your use-case.' },
      { title: 'Multilingual (Hindi, Gujarati, English)', desc: 'Speak to customers in their language.' },
      { title: 'Custom knowledge base', desc: 'Feed your docs, PDFs, product catalog — done.' },
      { title: 'Voice + Chat + WhatsApp', desc: 'One brain, every channel.' },
      { title: 'Analytics dashboard', desc: 'See intents, drop-offs, CSAT in real time.' },
      { title: 'Human handoff', desc: 'Escalate to your team when it matters.' },
    ],
    workflow: [
      { title: 'Discovery', desc: 'We map your workflows and pick the AI wins.' },
      { title: 'Data & Training', desc: 'Ingest data, fine-tune models, evaluate.' },
      { title: 'Integration', desc: 'Plug into CRM, ERP, WhatsApp, website.' },
      { title: 'Launch & Optimize', desc: 'Go live and iterate weekly with metrics.' },
    ],
    pricing: [
      { name: 'Starter', mrp: 49999, offer: 29999, popular: false, note: 'AI Chatbot for website', features: ['1 channel', '500 conversations/mo', 'Basic analytics', 'Email support'] },
      { name: 'Growth', mrp: 149000, offer: 89000, popular: true, note: 'Multi-channel AI Agent', features: ['3 channels (Web + WA + Voice)', '5,000 conversations/mo', 'Custom knowledge base', 'CRM integration', 'Priority support'] },
      { name: 'Enterprise', mrp: 499000, offer: 299000, popular: false, note: 'Custom AI + private cloud', features: ['Unlimited conversations', 'Fine-tuned model', 'On-prem / VPC deploy', 'Dedicated success manager', 'SLA 99.9%'] },
    ],
    subServices: ['AI Chatbots', 'AI Voice Assistant', 'AI Agents', 'Generative AI Applications', 'AI Document Processing', 'Predictive Analytics', 'Recommendation Engine', 'OCR Solutions', 'Computer Vision', 'AI Integration'],
    faqs: [
      { q: 'Which AI model do you use?', a: 'We pick the best-in-class for each use case — OpenAI GPT, Anthropic Claude, Google Gemini, or open-source Llama. You are never locked in.' },
      { q: 'Is my data safe?', a: 'Yes. We support private VPC deployment. Your data never trains public models.' },
      { q: 'How long to launch?', a: 'A production chatbot in 2–3 weeks. Complex agents in 6–8 weeks.' },
      { q: 'Do you support Hindi & Gujarati?', a: 'Absolutely — our stack supports 20+ Indian and global languages.' },
      { q: 'Do we own the AI?', a: 'Yes. Code, prompts, and fine-tuned models are yours.' },
    ],
    related: ['automation-solutions', 'data-analytics-bi', 'industry-software'],
  },
  {
    slug: 'website-development',
    name: 'Website Development',
    icon: 'Globe2',
    tagline: 'Websites that load in a blink and convert like magic.',
    heroSubtitle: 'From high-converting landing pages to enterprise portals — we build blazing-fast, SEO-first websites your customers love.',
    overview: 'We craft custom websites with Next.js, React and modern CMS platforms. Every site we ship is optimized for Core Web Vitals, SEO, accessibility and mobile-first design. From single landing pages to multi-region corporate portals — we cover the full spectrum with pixel-perfect design and blazing performance.',
    benefits: [
      { title: '3× faster than competitors', desc: 'Sub-second load times boost SEO and conversions.' },
      { title: 'SEO-optimized by default', desc: 'Rank higher without hiring an agency.' },
      { title: 'Mobile-first design', desc: 'Perfect on every screen size.' },
      { title: 'Own your code', desc: 'No vendor lock-in — full source handover.' },
    ],
    features: [
      { title: 'Next.js / React', desc: 'Modern, future-proof stack.' },
      { title: 'CMS included', desc: 'Edit content without a developer.' },
      { title: 'Multi-language ready', desc: 'Sell in Hindi, Gujarati and English.' },
      { title: 'Blog + SEO tools', desc: 'Rank on Google from day one.' },
      { title: 'Contact forms + CRM sync', desc: 'Every lead lands in your CRM.' },
      { title: 'Analytics & heatmaps', desc: 'See what your users actually do.' },
    ],
    workflow: [
      { title: 'Strategy', desc: 'Understand your brand, users and goals.' },
      { title: 'Design', desc: 'Wireframes, mockups and interactive prototypes.' },
      { title: 'Development', desc: 'Pixel-perfect, blazing-fast build.' },
      { title: 'Launch & Support', desc: 'Deploy, train and grow with you.' },
    ],
    pricing: [
      { name: 'Landing Page', mrp: 24999, offer: 14999, popular: false, note: 'Perfect for campaigns', features: ['1 conversion-focused page', 'Mobile responsive', 'Basic SEO', 'Contact form', '1 revision round'] },
      { name: 'Business Website', mrp: 89000, offer: 49999, popular: true, note: '5–8 page premium website', features: ['Up to 8 pages', 'Custom design', 'CMS included', 'Blog + SEO', 'CRM integration', '3 months support'] },
      { name: 'Enterprise / E-commerce', mrp: 299000, offer: 179000, popular: false, note: 'Custom web app or store', features: ['Unlimited pages / products', 'Payment gateway', 'Multi-language', 'Advanced SEO', 'Dedicated PM', '1 year support'] },
    ],
    subServices: ['Business Website', 'Corporate Website', 'E-commerce Website', 'Landing Pages', 'Portfolio Website', 'CMS Development', 'Custom Web Applications', 'UI/UX Design', 'Website Redesign', 'Website Maintenance'],
    faqs: [
      { q: 'How long does it take?', a: 'Landing page: 5–7 days. Business website: 3–4 weeks. E-commerce/Enterprise: 6–12 weeks.' },
      { q: 'Do I own the code?', a: 'Yes, 100%. Full source-code handover, no vendor lock-in.' },
      { q: 'Can I update content myself?', a: 'Absolutely — every website comes with an easy CMS.' },
      { q: 'Will it rank on Google?', a: 'We optimize for Core Web Vitals + on-page SEO from day one.' },
      { q: 'Do you provide hosting?', a: 'Yes, on AWS/Vercel/Google Cloud. Or deploy on your own.' },
    ],
    related: ['mobile-app-development', 'branding-creative', 'digital-marketing'],
  },
  {
    slug: 'mobile-app-development',
    name: 'Mobile App Development',
    icon: 'Smartphone',
    tagline: 'World-class apps for iOS, Android and everything in between.',
    heroSubtitle: 'Native performance, cross-platform economics. We build mobile apps that customers love and app stores feature.',
    overview: 'We build native and cross-platform mobile apps using Flutter, React Native, Swift and Kotlin. Whether you need a customer-facing e-commerce app, an internal CRM tool, or a delivery platform — we architect for scale, security and delight. Every app ships with analytics, crash reporting and OTA updates.',
    benefits: [
      { title: 'Native performance', desc: 'Feels instant, works offline.' },
      { title: 'iOS + Android from one codebase', desc: 'Save 40–50% vs building twice.' },
      { title: 'Play Store & App Store publishing', desc: 'We handle approvals end-to-end.' },
      { title: 'Push notifications + analytics', desc: 'Engage users and measure everything.' },
    ],
    features: [
      { title: 'Flutter / React Native / Native', desc: 'The right tech for your stack.' },
      { title: 'Offline mode', desc: 'Works with or without internet.' },
      { title: 'Payments (UPI, cards, wallets)', desc: 'Razorpay, Stripe, PayU ready.' },
      { title: 'Push + WhatsApp notifications', desc: 'Bring users back every day.' },
      { title: 'Backend + admin panel', desc: 'Complete solution, not just an app.' },
      { title: 'Store publishing included', desc: 'We ship to Play Store & App Store.' },
    ],
    workflow: [
      { title: 'Product Discovery', desc: 'Define features, users, revenue model.' },
      { title: 'UI/UX Design', desc: 'Interactive prototype you can click through.' },
      { title: 'Build & QA', desc: 'Agile sprints with weekly demos.' },
      { title: 'Launch & Grow', desc: 'Publish, iterate, and scale.' },
    ],
    pricing: [
      { name: 'MVP App', mrp: 149000, offer: 89000, popular: false, note: 'Launch in 6 weeks', features: ['Android OR iOS', '5–8 core screens', 'Basic backend', '1 payment gateway', '2 months support'] },
      { name: 'Growth App', mrp: 399000, offer: 249000, popular: true, note: 'Full production app', features: ['Android + iOS', '15–25 screens', 'Custom backend', 'Push + analytics', 'Play/App Store publishing', '6 months support'] },
      { name: 'Enterprise App', mrp: 999000, offer: 599000, popular: false, note: 'Complex, at scale', features: ['Unlimited screens', 'Microservices backend', 'Real-time features', 'Dedicated PM + designer', '1 year support', 'SLA'] },
    ],
    subServices: ['Android Apps', 'iOS Apps', 'Flutter Apps', 'React Native Apps', 'E-commerce Apps', 'CRM Apps', 'ERP Apps', 'Food Delivery Apps', 'Booking Apps', 'App Maintenance'],
    faqs: [
      { q: 'Should I build native or cross-platform?', a: 'For 90% of apps, Flutter or React Native gives 95% of native performance at 50% cost. We advise based on your use case.' },
      { q: 'Do you publish on stores?', a: 'Yes — Play Store & App Store submission, screenshots, ASO are included in Growth and Enterprise plans.' },
      { q: 'Do you provide backend?', a: 'Yes, full backend + admin panel is included.' },
      { q: 'How long to build?', a: 'MVP in 6 weeks. Growth in 3–4 months. Enterprise 6–12 months.' },
      { q: 'Post-launch support?', a: 'All plans include support. AMC available for long-term.' },
    ],
    related: ['website-development', 'ai-solutions', 'support-maintenance'],
  },
  {
    slug: 'support-maintenance',
    name: 'Support & Maintenance',
    icon: 'Wrench',
    tagline: 'Sleep peacefully. We keep everything running.',
    heroSubtitle: '24×7 monitoring, patches, backups and hands-on help — so your software never becomes a liability.',
    overview: 'From bug fixes and version upgrades to server monitoring and disaster recovery, our AMC (Annual Maintenance Contract) plans keep your critical software running at peak health. We offer proactive monitoring, weekly patch cycles, and SLA-backed response times so downtime never costs you customers.',
    benefits: [
      { title: '99.9% uptime guarantee', desc: 'Detect issues before your customers do.' },
      { title: 'Faster response than in-house', desc: 'Certified engineers on standby.' },
      { title: 'Predictable monthly cost', desc: 'Budget once, breathe easy all year.' },
      { title: 'Security patches on autopilot', desc: 'Stay compliant, stay safe.' },
    ],
    features: [
      { title: '24×7 monitoring', desc: 'Real-time alerts on servers, apps, APIs.' },
      { title: 'Daily automated backups', desc: 'Restore in minutes, not hours.' },
      { title: 'SLA-based response', desc: 'Critical tickets answered in <30 minutes.' },
      { title: 'Version upgrades', desc: 'Stay on latest secure releases.' },
      { title: 'Performance tuning', desc: 'Quarterly speed and cost audits.' },
      { title: 'Documentation + training', desc: 'Empower your team to self-serve.' },
    ],
    workflow: [
      { title: 'Audit & Onboarding', desc: 'Health-check your current setup.' },
      { title: 'Instrument & Monitor', desc: 'Add alerts, dashboards, backups.' },
      { title: 'Ongoing Support', desc: 'Ticket-based fixes + weekly patches.' },
      { title: 'Quarterly Review', desc: 'Report card + roadmap update.' },
    ],
    pricing: [
      { name: 'Basic AMC', mrp: 24999, offer: 14999, popular: false, note: 'Per month', features: ['Business-hours support', 'Bug fixes (up to 10/mo)', 'Weekly backups', 'Monthly report'] },
      { name: 'Standard AMC', mrp: 59999, offer: 39999, popular: true, note: 'Per month', features: ['24×7 support', 'Unlimited bug fixes', 'Daily backups', 'Performance tuning', 'Priority SLA'] },
      { name: 'Enterprise AMC', mrp: 149000, offer: 99000, popular: false, note: 'Per month', features: ['Dedicated engineer', '99.9% SLA', 'Security audits', 'Disaster recovery drills', 'On-site visits'] },
    ],
    subServices: ['AMC Support', 'Software Updates', 'Bug Fixes', 'Performance Optimization', 'Security Monitoring', 'Cloud Backup', 'Technical Support', 'Server Monitoring', 'Database Maintenance', 'Training & Documentation'],
    faqs: [
      { q: 'Do you support software we did not build?', a: 'Yes — we onboard 3rd-party or legacy systems after an initial audit.' },
      { q: 'What is your response time?', a: 'Critical: <30 min. High: <2 hrs. Medium: same day. Low: 48 hrs.' },
      { q: 'Is there a minimum contract?', a: 'AMC is annual, but we offer 3-month pilots for new clients.' },
      { q: 'Do you handle security patches?', a: 'Yes — CVE monitoring and patching are included in Standard and Enterprise.' },
      { q: 'Can you train our team?', a: 'Absolutely. Documentation + training sessions are included.' },
    ],
    related: ['cloud-devops', 'automation-solutions', 'business-consulting'],
  },
  {
    slug: 'branding-creative',
    name: 'Branding & Creative',
    icon: 'Palette',
    tagline: 'Brands people recognize. Brands people trust.',
    heroSubtitle: 'From your logo to your last Instagram reel — we design a brand system that turns strangers into fans.',
    overview: 'We build complete brand identity systems: logos, color palettes, typography, tone of voice, marketing collateral, packaging and motion assets. Whether you are launching new or refreshing an established brand, our designers turn your positioning into visuals that scale across every touchpoint.',
    benefits: [
      { title: 'Instant credibility', desc: 'Look like the leader you want to be.' },
      { title: 'Consistent everywhere', desc: 'One brand book, unlimited assets.' },
      { title: 'Higher price power', desc: 'Premium brands charge premium prices.' },
      { title: 'Faster team output', desc: 'Templates replace expensive back-and-forth.' },
    ],
    features: [
      { title: 'Logo + brand identity', desc: 'Primary, secondary, monochrome versions.' },
      { title: 'Brand guidelines PDF', desc: 'Colors, fonts, spacing, do’s & don’ts.' },
      { title: 'Social media templates', desc: 'Reusable Canva/Figma templates.' },
      { title: 'Print collateral', desc: 'Brochures, cards, letterheads, banners.' },
      { title: 'Packaging design', desc: 'Retail-ready, printer-approved files.' },
      { title: 'Motion + video', desc: 'Explainers, reels, ad edits.' },
    ],
    workflow: [
      { title: 'Brand Strategy', desc: 'Positioning, audience, tone of voice.' },
      { title: 'Logo & Identity', desc: '3 concepts, refine to the winner.' },
      { title: 'Guidelines & Assets', desc: 'Ship the full brand system.' },
      { title: 'Rollout', desc: 'Apply across website, social, print.' },
    ],
    pricing: [
      { name: 'Starter', mrp: 24999, offer: 14999, popular: false, note: 'Logo + basics', features: ['Logo (3 concepts)', 'Color + font system', 'Business card design', '1-page brand guide'] },
      { name: 'Brand Pack', mrp: 79999, offer: 49999, popular: true, note: 'Complete identity', features: ['Everything in Starter', 'Full brand guidelines (20+ pages)', 'Social media kit (10 templates)', 'Letterhead + envelope', 'Company profile PDF'] },
      { name: 'Brand Empire', mrp: 199000, offer: 129000, popular: false, note: 'Enterprise identity', features: ['Everything in Brand Pack', 'Packaging (up to 3 SKUs)', 'Motion logo + intro video', 'Photography direction', '6-month design retainer'] },
    ],
    subServices: ['Logo Design', 'Brand Identity', 'Social Media Creatives', 'Business Brochures', 'Company Profile', 'Packaging Design', 'UI Design', 'Motion Graphics', 'Video Editing', 'Presentation Design'],
    faqs: [
      { q: 'How many logo revisions?', a: '3 concepts + 3 rounds of refinement on the winner. We keep going till you love it.' },
      { q: 'Do we get editable files?', a: 'Yes — AI, PSD, Figma, SVG, PNG. All source files.' },
      { q: 'Timeline for full identity?', a: 'Starter: 1 week. Brand Pack: 3–4 weeks. Brand Empire: 6–8 weeks.' },
      { q: 'Do you print collateral?', a: 'We deliver print-ready files. Print production is optional add-on.' },
      { q: 'Can you refresh our existing logo?', a: 'Yes — rebrand and refresh projects are common. We audit first.' },
    ],
    related: ['website-development', 'digital-marketing', 'business-consulting'],
  },
  {
    slug: 'business-consulting',
    name: 'Business Consulting',
    icon: 'Briefcase',
    tagline: 'Strategy that ships. Not slides that gather dust.',
    heroSubtitle: 'From digital transformation to ERP selection — we help you make the right tech bets and execute them fast.',
    overview: 'Our senior consultants bring 20+ years of experience across manufacturing, retail, healthcare, real estate and services. We help you diagnose bottlenecks, prioritize the highest-ROI initiatives, choose the right technology, and roll it out with change management. No fluff — our engagements end with working software and measurable business outcomes.',
    benefits: [
      { title: 'Clarity in 2 weeks', desc: 'Know exactly what to build, in what order.' },
      { title: 'Avoid costly mistakes', desc: 'Do not buy the wrong ERP for 5 years.' },
      { title: 'Faster ROI', desc: 'Focus on the 20% that drives 80% of impact.' },
      { title: 'Change management done right', desc: 'Your team adopts, not resists.' },
    ],
    features: [
      { title: 'Digital maturity audit', desc: 'Scorecard across 10 dimensions.' },
      { title: 'Technology roadmap', desc: '12/24/36-month phased plan.' },
      { title: 'Vendor selection', desc: 'Unbiased RFP + shortlisting help.' },
      { title: 'Process re-engineering', desc: 'Redesign workflows before automating.' },
      { title: 'Change management', desc: 'Training, comms, adoption tracking.' },
      { title: 'Board / investor decks', desc: 'Fund-raise ready tech narrative.' },
    ],
    workflow: [
      { title: 'Diagnose', desc: 'Interviews, data, systems audit.' },
      { title: 'Design', desc: 'Future-state blueprint + roadmap.' },
      { title: 'Decide', desc: 'Build vs buy, vendor selection, budget.' },
      { title: 'Deliver', desc: 'Own execution or advise your team.' },
    ],
    pricing: [
      { name: 'Diagnostic', mrp: 79999, offer: 49999, popular: false, note: '2-week engagement', features: ['Stakeholder interviews', 'Systems audit', 'Bottleneck report', 'Priority roadmap'] },
      { name: 'Transformation', mrp: 299000, offer: 199000, popular: true, note: '3-month engagement', features: ['Everything in Diagnostic', 'Full technology roadmap', 'Vendor selection', 'Change plan', 'Weekly steering committee'] },
      { name: 'Fractional CTO', mrp: 499000, offer: 349000, popular: false, note: 'Per quarter', features: ['Senior CTO on retainer', 'Team leadership', 'Investor / board support', 'Architecture reviews', 'Hiring support'] },
    ],
    subServices: ['Digital Transformation', 'IT Consulting', 'Business Automation', 'Process Optimization', 'Startup Consultation', 'Technology Roadmap', 'Software Planning', 'ERP Consultation', 'CRM Strategy', 'Business Growth Planning'],
    faqs: [
      { q: 'Are you vendor-neutral?', a: 'Yes — we recommend the best tool for your case, even if it is not ours.' },
      { q: 'What size businesses do you serve?', a: 'From ₹5 Cr to ₹500 Cr revenue. Startups to enterprises.' },
      { q: 'Can you help us fund-raise?', a: 'Yes — we prepare technology-side of pitch decks and DD.' },
      { q: 'How is a consultant different from a developer?', a: 'Consultants decide WHAT to build and WHY. Developers build it. We do both under one roof.' },
      { q: 'Do you sign NDAs?', a: 'Always, before the first call.' },
    ],
    related: ['ai-solutions', 'automation-solutions', 'industry-software'],
  },
  {
    slug: 'digital-marketing',
    name: 'Digital Marketing',
    icon: 'TrendingUp',
    tagline: 'Predictable pipeline. Measurable ROI. Every month.',
    heroSubtitle: 'SEO, ads, social and automation — we run a full growth engine so you can focus on closing deals.',
    overview: 'From SEO and Google Ads to Meta, Instagram, LinkedIn, email and marketing automation, our performance marketing team builds a full-funnel growth engine. Every campaign is measured on revenue, not vanity. We report weekly on CPL, ROAS and pipeline generated — so you always know exactly what you are getting.',
    benefits: [
      { title: 'Predictable leads', desc: 'A steady flow, not feast-or-famine.' },
      { title: 'Lower CAC', desc: 'Full-funnel optimization drops cost 20–40%.' },
      { title: 'Own your organic engine', desc: 'SEO compounds every month.' },
      { title: 'Weekly transparent reports', desc: 'See every rupee, every result.' },
    ],
    features: [
      { title: 'SEO (technical + content)', desc: 'Rank on page 1 for buying keywords.' },
      { title: 'Google Ads', desc: 'Search, YouTube, Performance Max.' },
      { title: 'Meta / Instagram Ads', desc: 'Video-first creative + retargeting.' },
      { title: 'LinkedIn campaigns', desc: 'B2B lead-gen that actually works.' },
      { title: 'Email + WhatsApp automation', desc: 'Nurture leads on autopilot.' },
      { title: 'CRM integration', desc: 'Every lead syncs to your pipeline.' },
    ],
    workflow: [
      { title: 'Audit & ICP', desc: 'Understand your buyer + funnel.' },
      { title: 'Strategy & Creatives', desc: 'Channels, offers, ad creatives.' },
      { title: 'Launch & Optimize', desc: 'Run, measure, iterate weekly.' },
      { title: 'Scale', desc: 'Double down on what works.' },
    ],
    pricing: [
      { name: 'Starter', mrp: 39999, offer: 24999, popular: false, note: 'Per month + ad spend', features: ['1 channel (SEO or Ads)', 'Weekly reports', '1 landing page', 'Basic CRM sync'] },
      { name: 'Growth', mrp: 89999, offer: 59999, popular: true, note: 'Per month + ad spend', features: ['SEO + Google + Meta', 'Creative production (8/mo)', 'Landing pages (2/mo)', 'Marketing automation', 'Bi-weekly strategy calls'] },
      { name: 'Scale', mrp: 199000, offer: 149000, popular: false, note: 'Per month + ad spend', features: ['Full-funnel (SEO/Ads/Email/WA)', 'Dedicated growth manager', 'Unlimited creatives', 'Attribution dashboards', 'Weekly war-room'] },
    ],
    subServices: ['SEO', 'Google Ads', 'Meta Ads', 'Social Media Marketing', 'Instagram Marketing', 'LinkedIn Marketing', 'Email Marketing', 'Content Marketing', 'Lead Generation', 'Marketing Automation'],
    faqs: [
      { q: 'When will I see results?', a: 'Ads: leads in week 1. SEO: 3–6 months for sustainable rankings.' },
      { q: 'Do you manage ad spend?', a: 'Yes — you fund the ad accounts directly. We manage strategy, creatives, optimization.' },
      { q: 'How do you report?', a: 'Weekly dashboards, monthly strategy calls, quarterly business review.' },
      { q: 'Minimum contract length?', a: '3 months. SEO ideally 6+ months for compounding.' },
      { q: 'Do you write content?', a: 'Yes — blog posts, landing copy, ad copy, email copy — all included.' },
    ],
    related: ['branding-creative', 'website-development', 'automation-solutions'],
  },
  {
    slug: 'cloud-devops',
    name: 'Cloud & DevOps',
    icon: 'Cloud',
    tagline: 'Ship faster. Sleep better. Scale infinitely.',
    heroSubtitle: 'AWS, Azure, GCP + Docker, Kubernetes and CI/CD — we build cloud infra that never wakes you up at 3 AM.',
    overview: 'We design, migrate and operate cloud infrastructure on AWS, Azure and Google Cloud. From containerizing legacy apps with Docker/Kubernetes to setting up multi-region high-availability with automated CI/CD pipelines, our DevOps engineers build systems that scale gracefully and cost 30–50% less than mismanaged clouds.',
    benefits: [
      { title: '99.99% uptime', desc: 'Multi-AZ, auto-healing infra.' },
      { title: '30–50% cost savings', desc: 'Right-sizing and reserved instances.' },
      { title: 'Deploy 20× more often', desc: 'CI/CD unlocks fast, safe releases.' },
      { title: 'Enterprise security', desc: 'SOC2, ISO, HIPAA-ready patterns.' },
    ],
    features: [
      { title: 'Cloud migration', desc: 'From on-prem or shared hosting to AWS/Azure/GCP.' },
      { title: 'Docker + Kubernetes', desc: 'Containerize and orchestrate anything.' },
      { title: 'CI/CD pipelines', desc: 'GitHub Actions, GitLab, Jenkins, ArgoCD.' },
      { title: 'Infrastructure as Code', desc: 'Terraform, CloudFormation, reproducible.' },
      { title: 'Monitoring & alerting', desc: 'Grafana, Datadog, PagerDuty, Sentry.' },
      { title: 'DR + backup', desc: 'RTO < 1 hr, tested quarterly.' },
    ],
    workflow: [
      { title: 'Assess', desc: 'Current infra + cost + risk audit.' },
      { title: 'Design', desc: 'Target architecture + migration plan.' },
      { title: 'Migrate', desc: 'Move workloads safely with zero downtime.' },
      { title: 'Operate', desc: 'Monitor, patch, optimize continuously.' },
    ],
    pricing: [
      { name: 'Cloud Starter', mrp: 49999, offer: 29999, popular: false, note: 'One-time setup', features: ['1 environment', 'Basic monitoring', 'SSL + domain', 'Daily backups', '1 month support'] },
      { name: 'Cloud Pro', mrp: 149000, offer: 99000, popular: true, note: 'One-time + monthly ops', features: ['Multi-env (Dev/Stage/Prod)', 'Kubernetes cluster', 'CI/CD pipelines', 'Monitoring + alerting', '3 months support'] },
      { name: 'Enterprise Cloud', mrp: 499000, offer: 299000, popular: false, note: 'One-time + monthly ops', features: ['Multi-region HA', 'Full IaC (Terraform)', 'Security hardening', 'DR + compliance', 'Dedicated DevOps engineer'] },
    ],
    subServices: ['AWS Solutions', 'Microsoft Azure', 'Google Cloud', 'VPS Hosting', 'Dedicated Servers', 'Docker', 'Kubernetes', 'CI/CD Pipeline', 'SSL & Security', 'Backup & Disaster Recovery'],
    faqs: [
      { q: 'Which cloud is best?', a: 'Depends on your stack. We are certified partners of AWS, Azure and GCP.' },
      { q: 'Can you cut our AWS bill?', a: 'Yes — our average cost audit saves 30–45%.' },
      { q: 'How long is a migration?', a: 'Small apps: 2–4 weeks. Enterprise: 3–6 months, phased.' },
      { q: 'Zero-downtime migration?', a: 'Yes — blue-green + traffic shifting is our default pattern.' },
      { q: 'Do you handle security compliance?', a: 'SOC2, ISO 27001, HIPAA, PCI — we set up controls and prepare for audit.' },
    ],
    related: ['support-maintenance', 'automation-solutions', 'ai-solutions'],
  },
  {
    slug: 'automation-solutions',
    name: 'Automation Solutions',
    icon: 'Zap',
    tagline: 'Automate the boring. Amplify the brilliant.',
    heroSubtitle: 'WhatsApp, email, workflows, approvals and RPA — give your team back 10+ hours a week.',
    overview: 'We automate the repetitive work that drains your team — sending invoices, chasing approvals, syncing data between systems, following up on leads. Using low-code platforms, RPA bots and custom integrations, we turn week-long processes into minutes-long ones.',
    benefits: [
      { title: '10+ hours saved per week', desc: 'Per employee, on average.' },
      { title: 'Zero data-entry errors', desc: 'Bots do not typo.' },
      { title: 'Faster approvals', desc: 'Days become minutes.' },
      { title: 'Happier team', desc: 'They focus on creative, high-value work.' },
    ],
    features: [
      { title: 'WhatsApp Business API automation', desc: 'Broadcast, reply, book demos automatically.' },
      { title: 'Email + drip campaigns', desc: 'Nurture leads without lifting a finger.' },
      { title: 'Workflow builder', desc: 'Visual, no-code automation designer.' },
      { title: 'CRM + ERP automation', desc: 'Auto-create quotes, invoices, tasks.' },
      { title: 'Approval workflows', desc: 'Multi-level, mobile-friendly.' },
      { title: 'API + 3rd party integrations', desc: 'Connect any two tools you use.' },
    ],
    workflow: [
      { title: 'Process Map', desc: 'Document the workflow as-is.' },
      { title: 'Automation Design', desc: 'Identify the highest-ROI steps.' },
      { title: 'Build & Test', desc: 'Automate, sandbox, validate.' },
      { title: 'Rollout', desc: 'Deploy, train, monitor, iterate.' },
    ],
    pricing: [
      { name: 'Quick Win', mrp: 29999, offer: 17999, popular: false, note: 'One automation', features: ['1 workflow automated', 'Up to 3 integrations', 'Testing + training', '1 month support'] },
      { name: 'Business Pack', mrp: 89999, offer: 59999, popular: true, note: '5 workflows', features: ['5 workflows automated', 'Unlimited integrations', 'WhatsApp API setup', 'Dashboards', '3 months support'] },
      { name: 'RPA Enterprise', mrp: 299000, offer: 199000, popular: false, note: 'Custom RPA', features: ['Unlimited bots', 'Custom RPA (UiPath/Blue Prism style)', 'Approval workflows', 'SLA-backed ops', '1 year support'] },
    ],
    subServices: ['WhatsApp Automation', 'Email Automation', 'Workflow Automation', 'CRM Automation', 'ERP Automation', 'Invoice Automation', 'Approval Workflow', 'Robotic Process Automation (RPA)', 'API Integration', 'Third-party Integration'],
    faqs: [
      { q: 'What can be automated?', a: 'Anything repeatable: lead follow-up, invoicing, approvals, data entry, WhatsApp replies, reports.' },
      { q: 'Do you use RPA tools like UiPath?', a: 'Yes — UiPath, Automation Anywhere, or open-source equivalents.' },
      { q: 'WhatsApp Business API cost?', a: 'Meta charges per conversation. We help you set it up officially and cost-optimize.' },
      { q: 'Timeline for one automation?', a: 'Simple: 3–5 days. Complex RPA: 2–4 weeks.' },
      { q: 'ROI in numbers?', a: 'Typical clients save ₹5–25 lakh per year per full-time equivalent replaced.' },
    ],
    related: ['ai-solutions', 'industry-software', 'digital-marketing'],
  },
  {
    slug: 'industry-software',
    name: 'Industry-Specific Software',
    icon: 'Boxes',
    tagline: 'Not generic tools. Software built for your industry.',
    heroSubtitle: 'CRM, ERP, HRMS, POS, hospital, school, manufacturing — pre-built solutions ready to deploy in days, not months.',
    overview: 'Our industry vertical products come pre-loaded with workflows, reports and integrations for your business. Retail POS, School ERP, Hospital ERP, Manufacturing ERP, Real Estate CRM, Restaurant POS — each is battle-tested with 500+ deployments and configurable to your exact needs. Deploy in weeks, not years.',
    benefits: [
      { title: 'Ready in weeks', desc: 'Skip 12-month custom builds.' },
      { title: 'Industry best-practices baked in', desc: 'Learn from 500+ clients.' },
      { title: 'Configurable, not custom', desc: 'Flexibility without complexity.' },
      { title: 'Ongoing product updates', desc: 'New features every quarter.' },
    ],
    features: [
      { title: 'Vertical-specific workflows', desc: 'Not a generic template.' },
      { title: 'Multi-branch / multi-user', desc: 'Scale from 1 to 1,000 users.' },
      { title: 'Mobile apps included', desc: 'Owner, staff, customer apps.' },
      { title: 'GST + statutory reports', desc: 'Compliance out of the box.' },
      { title: 'WhatsApp + SMS + email', desc: 'Reach customers everywhere.' },
      { title: 'Dashboards + insights', desc: 'Real-time business health.' },
    ],
    workflow: [
      { title: 'Choose Product', desc: 'Pick the vertical that fits.' },
      { title: 'Configure', desc: 'Setup masters, users, roles.' },
      { title: 'Migrate & Train', desc: 'Import data + train your team.' },
      { title: 'Go Live', desc: 'Launch and grow with quarterly updates.' },
    ],
    pricing: [
      { name: 'Starter', mrp: 29999, offer: 17999, popular: false, note: 'Per year', features: ['Up to 5 users', '1 branch', 'Basic reports', 'Email support'] },
      { name: 'Business', mrp: 89999, offer: 59999, popular: true, note: 'Per year', features: ['Up to 25 users', 'Multi-branch', 'Custom reports', 'WhatsApp integration', 'Priority support'] },
      { name: 'Enterprise', mrp: 299000, offer: 199000, popular: false, note: 'Per year', features: ['Unlimited users', 'Custom modules', 'API access', 'Dedicated success manager', 'SLA 99.9%'] },
    ],
    subServices: ['CRM Software', 'ERP Software', 'HRMS', 'Billing Software', 'Inventory Management', 'School ERP', 'Hospital Management', 'Restaurant POS', 'Real Estate CRM', 'Manufacturing ERP', 'Gym Management', 'Service Management'],
    faqs: [
      { q: 'How is this different from Zoho / Tally / SAP?', a: 'We are cheaper, faster to deploy, and offer done-with-you setup + ongoing customization.' },
      { q: 'Can it be customized?', a: 'Yes — 90% via configuration, 10% via custom modules for Enterprise plans.' },
      { q: 'Do you migrate our old data?', a: 'Yes — Excel, Tally, other software — we handle migration.' },
      { q: 'On cloud or on-premise?', a: 'Both. Default is our cloud; on-prem available for Enterprise.' },
      { q: 'Do you provide training?', a: 'Yes — live sessions, videos and documentation — all included.' },
    ],
    related: ['business-ecosystem', 'automation-solutions', 'business-consulting'],
  },
  {
    slug: 'business-ecosystem',
    name: 'Business Ecosystem',
    icon: 'LayoutDashboard',
    tagline: 'One connected platform for every department.',
    heroSubtitle: 'CRM, ERP, HRMS, Inventory, POS, portals and BI — all under one roof, sharing one database.',
    overview: 'Stop juggling 12 disconnected tools. Our Business Ecosystem is a unified platform where sales, operations, finance, HR, customers and vendors all work in one connected system. One login, one master data, one source of truth — and 10× fewer sync errors.',
    benefits: [
      { title: 'One source of truth', desc: 'No more spreadsheets flying via email.' },
      { title: 'Real-time visibility', desc: 'See the whole business at a glance.' },
      { title: '10× fewer sync errors', desc: 'Integrated by design.' },
      { title: 'Vendor + customer portals', desc: 'Self-service reduces support 60%.' },
    ],
    features: [
      { title: 'Unified data model', desc: 'Master data flows across modules.' },
      { title: 'Role-based access', desc: 'Give each user exactly what they need.' },
      { title: 'Customer + vendor portals', desc: 'Self-service orders, invoices, tickets.' },
      { title: 'Mobile apps for every role', desc: 'Owner, sales, ops, HR — all mobile.' },
      { title: 'BI dashboards', desc: 'Executive, department and personal.' },
      { title: 'Accounting sync', desc: 'Auto-post to Tally / Zoho / Xero.' },
    ],
    workflow: [
      { title: 'Blueprint', desc: 'Map departments + integrations.' },
      { title: 'Modular Rollout', desc: 'Start with 2–3 modules, expand.' },
      { title: 'Portal Enablement', desc: 'Vendors + customers self-serve.' },
      { title: 'Insights & Growth', desc: 'BI dashboards drive decisions.' },
    ],
    pricing: [
      { name: 'Core', mrp: 149000, offer: 99000, popular: false, note: 'Per year', features: ['CRM + Billing + Inventory', 'Up to 15 users', 'Basic dashboards', 'Standard support'] },
      { name: 'Suite', mrp: 399000, offer: 249000, popular: true, note: 'Per year', features: ['All Core modules + HRMS + Accounting', 'Up to 50 users', 'Customer + vendor portals', 'BI dashboard', 'Priority support'] },
      { name: 'Ecosystem', mrp: 999000, offer: 649000, popular: false, note: 'Per year', features: ['All modules unlocked', 'Unlimited users', 'Custom modules', 'Dedicated success team', 'SLA 99.9%'] },
    ],
    subServices: ['CRM', 'ERP', 'HRMS', 'Inventory', 'Billing', 'POS', 'Accounting', 'Customer Portal', 'Vendor Portal', 'Employee Portal', 'Mobile Apps', 'Business Intelligence Dashboard'],
    faqs: [
      { q: 'Do we have to buy every module?', a: 'No — start with 2–3, add more anytime.' },
      { q: 'Can it integrate with Tally / Zoho?', a: 'Yes — accounting sync is built-in.' },
      { q: 'What about our existing software?', a: 'We integrate via API or replace step-by-step.' },
      { q: 'Migration timeline?', a: 'Core suite: 4–6 weeks. Full ecosystem: 3–6 months.' },
      { q: 'Do you offer training?', a: 'Yes — role-based training + videos + docs — unlimited.' },
    ],
    related: ['industry-software', 'data-analytics-bi', 'automation-solutions'],
  },
  {
    slug: 'data-analytics-bi',
    name: 'Data Analytics & BI',
    icon: 'BarChart3',
    tagline: 'Turn data into decisions. Instantly.',
    heroSubtitle: 'Live dashboards, predictive models and executive KPIs — so every meeting starts with facts, not opinions.',
    overview: 'We build enterprise-grade BI dashboards and analytics products on Power BI, Tableau, Metabase and custom stacks. From sales and inventory dashboards to predictive analytics models forecasting demand or churn, our data team turns your raw data into decisions that ship.',
    benefits: [
      { title: 'Decisions in seconds', desc: 'Instead of days of Excel wrangling.' },
      { title: 'Predict, not just report', desc: 'Forecast demand, churn, revenue.' },
      { title: 'One version of the truth', desc: 'No more “whose number is right”.' },
      { title: 'Mobile executive dashboards', desc: 'Board-ready insights on the go.' },
    ],
    features: [
      { title: 'Power BI + Tableau + custom', desc: 'Best tool for each use case.' },
      { title: 'Sales / inventory / HR / finance', desc: 'Prebuilt templates for every function.' },
      { title: 'Predictive analytics', desc: 'Demand, churn, LTV, credit-risk models.' },
      { title: 'KPI + OKR dashboards', desc: 'Track what matters weekly.' },
      { title: 'Auto-refresh + alerts', desc: 'Nudged before problems happen.' },
      { title: 'Custom + regulatory reports', desc: 'GST, TDS, board packs — automated.' },
    ],
    workflow: [
      { title: 'Data Audit', desc: 'Source systems + data quality check.' },
      { title: 'Warehouse + ETL', desc: 'Clean, model, load, transform.' },
      { title: 'Dashboards + Models', desc: 'Build BI + predictive layers.' },
      { title: 'Adoption', desc: 'Train teams + weekly review rituals.' },
    ],
    pricing: [
      { name: 'Insights Starter', mrp: 49999, offer: 29999, popular: false, note: 'One-time', features: ['1 department dashboard', 'Up to 3 data sources', 'Basic KPIs', '1 month support'] },
      { name: 'BI Pro', mrp: 149000, offer: 99000, popular: true, note: 'One-time + AMC', features: ['3–5 dashboards', 'Data warehouse setup', 'Predictive model (1)', 'Auto-refresh + alerts', '3 months support'] },
      { name: 'Data Enterprise', mrp: 499000, offer: 299000, popular: false, note: 'One-time + AMC', features: ['Unlimited dashboards', 'Full data platform', 'Multiple ML models', 'Executive mobile app', 'Dedicated data engineer'] },
    ],
    subServices: ['Power BI Dashboard', 'Business Analytics', 'Sales Dashboard', 'Customer Analytics', 'Inventory Analytics', 'HR Analytics', 'Financial Reports', 'KPI Dashboard', 'Predictive Analytics', 'Custom Reports'],
    faqs: [
      { q: 'Power BI or Tableau?', a: 'Depends on team + budget. We are certified in both.' },
      { q: 'Do you build predictive models?', a: 'Yes — demand forecasting, churn, credit risk, LTV, and more.' },
      { q: 'Where does the data come from?', a: 'CRM, ERP, POS, Excel, Google Sheets, databases — we integrate all.' },
      { q: 'How long for the first dashboard?', a: 'Insights Starter: 2 weeks. BI Pro: 4–6 weeks.' },
      { q: 'Do you host the data?', a: 'Optional — host on your cloud or ours.' },
    ],
    related: ['ai-solutions', 'business-ecosystem', 'industry-software'],
  },
]

export function getCategoryBySlug(slug) {
  return SERVICE_CATEGORIES.find(c => c.slug === slug)
}

export function getCategoryList() {
  return SERVICE_CATEGORIES.map(c => ({ slug: c.slug, name: c.name, icon: c.icon, tagline: c.tagline }))
}
